### ISSUE TITLE
Cannot install pysvb into stellarmate os

### ISSUE THREAD

**Issue by jctk** [olosnet/pysvb#1]
I tried to install into stellarmate os on Raspberry PI 4B.
That OS is 64bit arm linux.

```console
$ pip install file:///home/stellarmate/pysvb-main/
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./pysvb-main
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8z8wszgg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8z8wszgg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-trf2vvg_
         cwd: /tmp/pip-req-build-8z8wszgg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8z8wszgg/setup.py", line 38, in <module>
        raise Exception("Error: unsupported platform: {}".format(machine))
    Exception: Error: unsupported platform: aarch64
    ----------------------------------------
```

I was able to install by adding 'aarch64' to armv8_arch at line 16 of setup.py.

**Comment by olosnet** [comment]
Updated with the change
